# Generated by Django 2.0.4 on 2018-04-24 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=380)),
            ],
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tagged_memes', models.ManyToManyField(to='Main_Meme.Meme')),
            ],
        ),
        migrations.CreateModel(
            name='Vot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative')], null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voted_meme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_Meme.Meme')),
            ],
        ),
        migrations.CreateModel(
            name='CommentComment',
            fields=[
                ('comentari_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main_Meme.Comentari')),
            ],
            bases=('Main_Meme.comentari',),
        ),
        migrations.CreateModel(
            name='MemeComment',
            fields=[
                ('comentari_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Main_Meme.Comentari')),
                ('commented_meme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_Meme.Meme')),
            ],
            bases=('Main_Meme.comentari',),
        ),
        migrations.AddField(
            model_name='comentari',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentcomment',
            name='related_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='Main_Meme.Comentari'),
        ),
    ]
