# Generated by Django 2.0.4 on 2018-04-21 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main_Meme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=380)),
                ('num_comments', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_of_Meme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_Meme.Meme')),
                ('comment_of_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main_Meme.Comentari')),
            ],
        ),
    ]
