# Generated by Django 2.0.4 on 2018-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Meme', '0003_vot'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentari',
            name='Title',
            field=models.CharField(default='No title', max_length=50),
            preserve_default=False,
        ),
    ]
