# Generated by Django 2.0.4 on 2018-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('Main_Meme', '0004_comentari_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('memetag', models.ManyToManyField(to='Main_Meme.Meme')),
            ],
        ),
    ]
