# Generated by Django 2.0.4 on 2018-04-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Meme', '0005_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='tags',
            name='memetag',
        ),
        migrations.RenameField(
            model_name='comentari',
            old_name='comment_of_Meme',
            new_name='commented_Meme',
        ),
        migrations.RenameField(
            model_name='comentari',
            old_name='comment_of_comment',
            new_name='commented_comment',
        ),
        migrations.RenameField(
            model_name='comentari',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='meme',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='vot',
            old_name='Meme_vote',
            new_name='voted_meme',
        ),
        migrations.RemoveField(
            model_name='comentari',
            name='num_comments',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='puntuation_votes',
        ),
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.DeleteModel(
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='tagged_memes',
            field=models.ManyToManyField(to='Main_Meme.Meme'),
        ),
    ]
