# Generated by Django 2.0.4 on 2018-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Meme', '0006_auto_20180423_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='published_date',
        ),
        migrations.AddField(
            model_name='vot',
            name='value',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Positive'), (2, 'Negative')], null=True),
        ),
    ]
